---
name: Report coverage

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  # https://github.community/t/permissions-nesecary-to-comment-on-a-pr/179047/5
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: centos-stream-8
            shortcut: cs8
            container-name: el8stream
          - name: centos-stream-9
            shortcut: cs9
            container-name: el9stream
    name: ${{ matrix.name }}
    container:
      image: quay.io/ovirt/buildcontainer:${{ matrix.container-name }}

    steps:
      # Requried for python3-isort on cs8
      - name: Prepare CentOS Stream 8 environment
        if: ${{ matrix.shortcut == 'cs8' }}
        run: |
          dnf copr enable -y sbonazzo/EL8_collection

      # Requried for python3-isort on cs9
      - name: Prepare CentOS Stream 9 environment
        if: ${{ matrix.shortcut == 'cs9' }}
        run: |
          dnf copr enable -y sbonazzo/EL9Collection

      - name: Install dependencies
        run: |
          dnf install -y epel-release
          dnf install -y --setopt=tsflags=nodocs \
            python3-coverage \
            python3-html2text \
            python3-isort \
            python3-pycodestyle \
            python3-pyflakes \
            vdsm-client \
            vdsm-jsonrpc \
            vdsm-python

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Test code
        run: |
          mkdir -p exported-artifacts
          mkdir -p tmp.repos
          ./autogen.sh --system
          make check
          make test
          coverage html \
            -d exported-artifacts/coverage_html_report \
            --rcfile="${PWD}/automation/coverage.rc"
          cp automation/index.html exported-artifacts/

      - name: Comment PR with coverage data
        run: |
          html2text --ignore-images --ignore-links -b 0 exported-artifacts/coverage_html_report/index.html |\
          sed "s:# Coverage report:# Coverage report for ${{ matrix.container-name }}:" > pr_comment
          MESSAGE="$(cat pr_comment)"
          gh pr comment "${{ github.event.pull_request.number }}" --body "${MESSAGE}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
